# Generated by Django 4.2.7 on 2023-11-23 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live_score', models.PositiveSmallIntegerField(default=0)),
                ('draft_score', models.PositiveSmallIntegerField(default=0)),
                ('backlink_count', models.IntegerField(default=0)),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo_stats', to='wagtailcore.page')),
            ],
            options={
                'verbose_name_plural': 'Page stats',
            },
        ),
    ]
